baseURL = 'https://danielschaaff.com'
languageCode = 'en-us'
title = "Daniel Schaaff"
defaultContentLanguage = "en"
paginate = 40
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[module]
[[module.imports]]
path = 'github.com/luizdepra/hugo-coder'

theme = "hugo-coder"
[params]
author = "Daniel Schaaff"
description = "My humble home on the internet."
info = ["He/Him/His", "DevOps", "Kubernetes", "Yaml Wrangling", "Guitar"]
keywords = "blog,developer,personal"
avatarURL = "images/avatar.jpg"
#gravatar = "daniel@danielschaaff.com"
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
since = 2010

[[languages.en.menu.main]]
name = "Blog"
weight = 3
url = "posts/"

[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/dschaaff/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/papaschaaff/"

[[params.social]]
name = "Mastodon"
rel = "me"
icon = "fa fa-2x fa-mastodon"
weight = 3
url = "https://hachyderm.io/@papaschaaff"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/danielschaaff/"

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://danielschaaff.com/index.xml"
rel = "alternate"
type = "application/rss+xml"
